# Generated by Django 3.0.5 on 2020-04-24 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('bsb', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company', max_length=200)),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_gateway.BankAccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('SUCCESSFUL', 'successful'), ('FAILED', 'failed'), ('DISPUTED', 'disputed')], help_text='Payment status', max_length=200)),
                ('created_on', models.DateTimeField(help_text='Time of creation')),
                ('transacted_on', models.DateTimeField(help_text='Time of transaction')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_gateway.Company')),
            ],
        ),
    ]
