# Generated by Django 3.0.5 on 2020-04-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of creation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transacted_on',
            field=models.DateTimeField(auto_now=True, help_text='Time of transaction'),
        ),
    ]
