# Generated by Django 3.0.5 on 2020-04-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_auto_20200425_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('SUCCESSFUL', 'successful'), ('FAILED', 'failed'), ('DISPUTED', 'disputed')], default='created', help_text='Payment status', max_length=20),
        ),
    ]
